import Head from 'next/head';
import React from 'react';
import Footer from '../footer';
import Navbar from '../Navbar';

function RootLayout({ children, tittle }) {
  return (
    <>
      <Head>
        <title>GJI PRO | {tittle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}

export default RootLayout;
